// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not supported for this application.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not supported for this application.');
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not supported for this application.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported for this application.');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuwnWpczjEUJ_D67D7lJzgBzSkFjPOveU',
    appId: '1:737005580488:android:a16481ea85f6e3ab2475fd',
    messagingSenderId: '737005580488',
    projectId: 'spending-income-tracker',
    storageBucket: 'spending-income-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0PlDBQVQ-xnXMVSZBb3ZhhFgAfI9-vN8',
    appId: '1:737005580488:ios:45fe32ed6c3c4cd22475fd',
    messagingSenderId: '737005580488',
    projectId: 'spending-income-tracker',
    storageBucket: 'spending-income-tracker.firebasestorage.app',
    iosClientId: '737005580488-6vkg03g1bhhse7rlr2uai8fdtmrhrqu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendingIncome',
  );

}